### ISSUE TITLE
help can i have access to edit

### ISSUE THREAD

**Issue by Relaxolotl07** [ameek2/NEC_app#31]
Yo im continuing from Dr. Albert's NEC lab and I can't push this code without access.

**Comment by ajmeek** [comment]
Hi, no problem. I just sent you an invite to collaborate, which you should see on your GitHub soon. Just accept that and you should be good to go. I can meet with you sometime if you want and discuss as much as I remember from the project if you'd find that helpful. Rhea should also be a useful contact, try reaching out to her as well.

**Comment by ajmeek** [comment]
Since you gave me a thumbs up on the previous post I'll close this issue now. Again though, feel free to contact me if you need some help.
